### ISSUE TITLE
Show case

### ISSUE THREAD

**Issue by kevinhwang91** [kevinhwang91/fzf-tmux-script#1]
![2020-02-28-12-53-50-lanczos](https://user-images.githubusercontent.com/17562139/75963942-568e6500-5f01-11ea-8b9c-b14ca9f50dc1.gif)

**Comment by kevinhwang91** [comment]
![fzf-tmux-popup-demo](https://user-images.githubusercontent.com/17562139/77829950-406e7000-7160-11ea-85aa-0f966feeb237.gif)

**Comment by liyechen** [comment]
v2ex来的，请问你是怎么出发fzf的捏？tab还是？

**Comment by kevinhwang91** [comment]
> v2ex来的，请问你是怎么出发fzf的捏？tab还是？

有tab也有zsh的keybind，要自己设置，感兴趣可以参考我的dotfile。

**Comment by liyechen** [comment]
> > v2ex来的，请问你是怎么出发fzf的捏？tab还是？
> 
> 有tab也有zsh的keybind，要自己设置，感兴趣可以参考我的dotfile。

OK 3q
