### ISSUE TITLE
Problems replicating popups demonstration

### ISSUE THREAD

**Issue by felipewarrener** [kevinhwang91/fzf-tmux-script#10]
I am having trouble replicating the functionality you showcased in your 'popups' demonstration video (https://user-images.githubusercontent.com/17562139/77829950-406e7000-7160-11ea-85aa-0f966feeb237.gif)

Could you please share your .tmux.conf, fzfp wrapper scripts, and any other configuration that makes this possible? For example, opening a file selected inside of the popup window inside of a vim buffer. Not sure how you are performing different send-keys functions on the same popup?

CONFIG PLZ :)

**Comment by kevinhwang91** [comment]
It's zsh completion + fzf + tmux. You can refer to my dotfiles. https://github.com/kevinhwang91/dotfiles/tree/main/zsh/lplug/fzf, but my zsh config is complicated for others.

> opening a file selected inside of the popup window inside of a vim buffer.

I don't use its feature, but you can use fzf.vim, it supports the tmux popup selecting in vim.

**Comment by felipewarrener** [comment]
In the video, you get a popup, and then you select a file and sent it to pane 1 and it opens in neovim?... How do you do this?

**Comment by kevinhwang91** [comment]
type `nvim <C-t>` `<C-t>` has bind from  `fzf-find-widget` under `zsh/lplug/fzf`
