### ISSUE TITLE
Strange issue with $FZF_DEFAULT_OPTS

### ISSUE THREAD

**Issue by eggbean** [kevinhwang91/fzf-tmux-script#11]
`fzfp` does not seem to work when I set `$FZF_DEFAULT_OPTS` using multi-lines.

```
  export FZF_DEFAULT_OPTS='
    --ansi
    --reverse
    --bind=ctrl-a:toggle-all
    --bind=ctrl-alt-j:preview-down
    --bind=ctrl-alt-k:preview-up
    --bind=ctrl-d:preview-page-down
    --bind=ctrl-u:preview-page-up
    --bind=alt-bs:clear-query
    --bind=ctrl-h:deselect
    --bind=ctrl-l:select
    --color fg:#F8F8F2
    --color fg+:#F8F8F2
    --color bg:-1
    --color bg+:-1
    --color hl:#50FA7B
    --color hl+:#FFB86C
    --color info:#BD93F9
    --color prompt:#50FA7B
    --color pointer:#FF79C6
    --color marker:#FF5555
    --color spinner:#8BE9FD
    --color header:#8BE9FD
  '
```
But if I use J in vim to join the lines into one line, it works. If I `echo $FZF_DEFAULT_OPTS` in each case, they are identical.

**Comment by kevinhwang91** [comment]
I can't reproduce the issue, work as expected in fzf and fzfp.

**Comment by eggbean** [comment]
This is how your script interprets the two different forms of the variable:

* Single line (working)

`envs='SHELL=/bin/bash FZF_DEFAULT_OPTS=\ --reverse\ --ansi\ --bind=ctrl-a:toggle-all\ --bind=ctrl-alt-j:preview-down\ --bind=ctrl-alt-k:preview-up\ --bind=ctrl-d:preview-page-down\ --bind=ctrl-u:preview-page-up\ --bind=alt-bs:clear-query\ --bind=ctrl-h:deselect\ --bind=ctrl-l:select\ --color\ fg:#F8F8F2\ --color\ fg+:#F8F8F2\ --color\ bg:-1\ --color\ bg+:-1\ --color\ hl:#50FA7B\ --color\ hl+:#FFB86C\ --color\ info:#BD93F9\ --color\ prompt:#50FA7B\ --color\ pointer:#FF79C6\ --color\ marker:#FF5555\ --color\ spinner:#8BE9FD\ --color\ header:#8BE9FD\ '`

* Multi-line (not working)

`envs='SHELL=/bin/bash FZF_DEFAULT_OPTS=$'\''\n  --reverse\n  --ansi\n  --bind=ctrl-a:toggle-all\n  --bind=ctrl-alt-j:preview-down\n  --bind=ctrl-alt-k:preview-up\n  --bind=ctrl-d:preview-page-down\n  --bind=ctrl-u:preview-page-up\n  --bind=alt-bs:clear-query\n  --bind=ctrl-h:deselect\n  --bind=ctrl-l:select\n  --color fg:#F8F8F2\n  --color fg+:#F8F8F2\n  --color bg:-1\n  --color bg+:-1\n  --color hl:#50FA7B\n  --color hl+:#FFB86C\n  --color info:#BD93F9\n  --color prompt:#50FA7B\n  --color pointer:#FF79C6\n  --color marker:#FF5555\n  --color spinner:#8BE9FD\n  --color header:#8BE9FD\n'\'''`

```
$ bash --version
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
```

**Comment by eggbean** [comment]
**SOLUTION:**
Double quotes and continuation backslashes

```
export FZF_DEFAULT_OPTS=" \
  --ansi \
  --reverse \
  --bind=ctrl-a:toggle-all \
  --bind=ctrl-alt-j:preview-down \
  --bind=ctrl-alt-k:preview-up \
  --bind=ctrl-d:preview-page-down \
  --bind=ctrl-u:preview-page-up \
  --bind=alt-bs:clear-query \
  --bind=ctrl-h:deselect \
  --bind=ctrl-l:select \
  --color fg:#F8F8F2 \
  --color fg+:#F8F8F2 \
  --color bg:-1 \
  --color bg+:-1 \
  --color hl:#50FA7B \
  --color hl+:#FFB86C \
  --color info:#BD93F9 \
  --color prompt:#50FA7B \
  --color pointer:#FF79C6 \
  --color marker:#FF5555 \
  --color spinner:#8BE9FD \
  --color header:#8BE9FD \
"

```
