### ISSUE TITLE
Column Widths

### ISSUE THREAD

**Issue by jrock2004** [kevinhwang91/fzf-tmux-script#12]
Just found this out and this is really awesome. How can change the width of the first column?

![image](https://github.com/kevinhwang91/fzf-tmux-script/assets/655716/dcf36752-c81e-471b-b1b6-2f3d82e72082)

**Comment by jrock2004** [comment]
I am guessing somewhere here is what I want

```
        # my personally configuration
        if (( id_cnt == 2 )); then
            local w_size=($(tmux display-message -p '#{window_width} #{window_height}'))
            local w_wid=${w_size[0]}
            local w_hei=${w_size[1]}
            local layout
            if (( 9*w_wid > 16*w_hei )); then
                layout='even-horizontal'
            else
                layout='even-vertical'
            fi
        else
            layout='titled'
        fi
```

**Comment by kevinhwang91** [comment]
Change second field `-9s`
https://github.com/kevinhwang91/fzf-tmux-script/blob/27bd13c0a3653a4a8a7c2d1a23b03649f504392b/panes/fzf-panes.tmux#L108
https://github.com/kevinhwang91/fzf-tmux-script/blob/27bd13c0a3653a4a8a7c2d1a23b03649f504392b/panes/fzf-panes.tmux#L154

**Comment by jrock2004** [comment]
@kevinhwang91 So changing the 2nd number made the column wider but the text is still ellipsed at same point

![image](https://github.com/kevinhwang91/fzf-tmux-script/assets/655716/d9568b82-a956-4437-8f2a-18a417216887)
