### ISSUE TITLE
fish shell errors

### ISSUE THREAD

**Issue by muralikodali** [kevinhwang91/fzf-tmux-script#4]
program is working, but configuration code is throwing errors in fish shell. can you please give equivalent fish code for configuration ?

**Comment by kevinhwang91** [comment]
I had tested in fish just now, the code of tmux's configuration is no issue under tmux 3.0.
Make sure your version of tmux is at least 3.0.
And I found that an issue about the preview in fzf because of fish, I had committed the patch, please update the lasted code.

**Comment by muralikodali** [comment]
I have updated my code to the latest one. I am getting error like this :  
/home/xxxx/.tmux.conf:212:unknown command: }
home/xxxx/.tmux.conf:215:unknown command: }

**Comment by kevinhwang91** [comment]
Make sure your version of tmux is at least 3.0.
`if-shell {} {}` is supported since 3.0.

**Comment by muralikodali** [comment]
After updating tmux to version 3.0 as suggested by you, there are no more errors.
