### ISSUE TITLE
Gotta navigate to all panes instances in order for them to be shown in the query list

### ISSUE THREAD

**Issue by josefson** [kevinhwang91/fzf-tmux-script#5]
I generally script the creation of tmux sessions(windows/panes). So i dont "go-inside" to all the panes that were created.
The error i'm getting is reproducible:

1. By having a session with multiple panes created by something like tmuxitanor
2. By creating another session and hitting Prefix-w
   - It will only show the focused session-pane.

Bellow i show you a screenshot in which i know to be 4 panes across 2 windows, but fzf-tmux-pane only sees the first one with the focus on.

![image](https://user-images.githubusercontent.com/5399654/87619556-7113ee80-c6ea-11ea-89ff-76aa827e67fc.png)

Now i went manually and focused every pane and rerun the Prefix+w, which makes it see all the other panes.

![image](https://user-images.githubusercontent.com/5399654/87619671-bafcd480-c6ea-11ea-883a-72ea47685d09.png)

**Comment by kevinhwang91** [comment]
Thanks for your feedback, I also can reproduce this issue.
For now, fzf-panes only use focused panes as source of fzf, I think I should join unfocused panes into the source.

**Comment by josefson** [comment]
I'd appreciate it. I've been trying to redirect my workflow in a way i could have direct access to panes across sessions.
Tmux choose-tree kinda does this... but its search capability is trash and in order to use the numbers to jump to the desired pane, one gotta spoofread the whole thing.
I've also tried fzf default tmux examples but their sources are only within the session for panes.
Anyhow, i'd appreciate your help if this would be possible.

**Comment by kevinhwang91** [comment]
done! It should work after you update the script.
