### ISSUE TITLE
no panes show up

### ISSUE THREAD

**Issue by ferdinandyb** [kevinhwang91/fzf-tmux-script#7]
I used this minimal config with `tmux -f [config]`

```
set -s focus-events on
# install powerline

# set ctrl space as command
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix


# some stuff
set -g default-terminal "tmux-256color"
# set -g default-terminal 'screen-256color'
set -g history-limit 10000



set -s focus-events on

# replace ~/.local/bin/fzf-panes.tmux to your path of fzf-panes.tmux
if-shell '[ -f ~/.tmux/scripts/fzf-panes.tmux ]' {
#   if you want to exclude specified session, please set @fzf_panes_ex_session_pat
#   for example, value equal to '^(floating)$', will exclude panes in session named 'floating'
#    set -g '@fzf_panes_ex_session_pat' '^(floating)$'
    set-hook -g pane-focus-in[10] \
    "run -b 'bash ~/.tmux/scripts/fzf-panes.tmux update_mru_pane_ids'"
    bind w run -b 'bash ~/.tmux/scripts/fzf-panes.tmux new_window'
    bind \; run -b 'bash ~/.tmux/scripts/fzf-panes.tmux selectscripts/f_last_pane'
} {
    set-hook -ug pane-focus-in[10]
    bind w choose-tree -Z
}
```

And instead of my prompt I get lines like `%2 %1` placed in copied mode when starting up and when pressing prefix+w. After pressing a few enters I get to the search panes window, but there are no panes in it, even though I have 3 open.

I'm using the latest tmux from the repo, but the no panes showing up thing was already present in 3.1c. Do you have any idea what might be going on? Your tool looks really cool and I'd like to use it :)

**Comment by kevinhwang91** [comment]
Thanks a lots, forgive my mistake in https://github.com/kevinhwang91/fzf-tmux-script/commit/a1f0410b0c090d66649263ecfbde8ddcd170233a, I use a popup window session, so I have set `@fzf_panes_ex_session_pat`, careless for testing.

The issue is fixed, please update the repository.
