### ISSUE TITLE
fzfp error: unknown option.

### ISSUE THREAD

**Issue by nerd190** [kevinhwang91/fzf-tmux-script#8]
Thank you for the scripts! :)

I get an error running the popup though:

```
$ ls --color=always | fzfp --ansi --width=50% --height=50%
unknown option: --width=50%
```

Tmux version: 3.1c

Thanks again!

**Comment by kevinhwang91** [comment]
Please upgrade tmux to 3.2 later.

>popup feature hasn't released in a stable tmux version.

**Comment by mdegis** [comment]
I got the same error (I guess?)

```bash
 
$ ls | fzfp --ansi --width=50% --height=50%
awk: syntax error at source line 1
 context is
        {match($0, >>>  /[0-9]+\.[0-9]+/, <<<
awk: illegal statement at source line 1
awk: illegal statement at source line 1
unknown option: --width=50%
```

Here is my tmux version:
```bash
$ tmux -V
tmux 3.3a
```

**Comment by eggbean** [comment]
I had the same issue for a long time. I didn't know why it worked sometimes and sometimes it didn't.

Realised that it was working on RHEL-based servers but not on Debian-based.

Then I looked at the awk version:

```
% awk --version
mawk 1.3.4 20230525
Copyright 2008-2022,2023, Thomas E. Dickey
Copyright 1991-1996,2014, Michael D. Brennan

random-funcs:       arc4random_stir/arc4random
regex-funcs:        internal

compiled limits:
sprintf buffer      8192
maximum-integer     9223372036854775808
```

`fzfp` doesn't seem to work with `mawk`. You need to install `GNU awk`, `gawk`. `awk` gets aliased to `gawk` and overrides `mawk` when it's installed.
